apiVersion: v1
kind: Service
metadata:
  name: api-service-loadbalancer
  namespace: tb-k8-nagp-2024
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer