apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-postgres-pvc
  namespace: tb-k8-nagp-2024
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard